### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by GermanBluefox**

### CODE REVIEW

**Comment by angelnu** [comment]
Merged.

I assume this is the preparation to move it under the ioBroker project, right?

**Comment by GermanBluefox** [comment]
Nor exactly. Do you want to move to iobroker?

**Comment by angelnu** [comment]
You request was to set https://github.com/ioBroker/ioBroker.chromecast as homepage. This does not exists until the adapter sources are moved under the iobroker project, right?

I am using it myself at home without incidences for the last two weeks so I think it could be made part of iobroker and being offered in the list of adapters available in iobroker.admin.

What would be the next steps to do so?

**Comment by GermanBluefox** [comment]
May be I am lost in communication :) to much conversation last time.
Do you want to have the adapter under github/iobroker or do you want to
have it under your account?
If yes (iobroker ), so I will fork this project and change the links.
If not, so leave everything as is.

I inserted yesterday chromecast into repository and the links were wrong.
22 Янв 2016 г. 16:35 пользователь "Vegetto" <notifications@github.com>
написал:

**Comment by angelnu** [comment]
Yes, willing to integrate into iobroker and be the maintainer of the adapter there.

I already merged your pull request so the links should be fine now. I should publish a new version to npm to reflect the new git repository. I added you as contributor there.

Btw: I tested the chromecast adapter with the latest releases of vis and the controller adapters and the chromecast widget now works without the need for any pfixes :-)

**Pull request merged**
